[global]
; Global configuration
pid = /tmp/php-fpm.pid
error_log = /proc/self/fd/2
log_level = notice

; Pool Configuration
[www]
;user = www
;group = www
listen = 9000
listen.backlog = 511
pm = dynamic
pm.max_children = 16
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 4
pm.max_requests = 1000
;pm.max_requests_grace_period = 30s
pm.process_idle_timeout = 10s
pm.status_path = /status
ping.path = /ping
ping.response = pong
access.log = /proc/self/fd/2
clear_env = no

; Production security settings
catch_workers_output = yes
decorate_workers_output = no

